### ISSUE TITLE
Games have to be in a subdirectory of the launcher

### ISSUE THREAD

**Issue by naturally-intelligent** [MrEliptik/game_launcher#12]
Now I'm not sure if this is an issue or not, but as I understand it, games have to be installed in the launcher's subdirectory.

Is this true?  Is there a way around this?  Can we use batch files / shortcuts?  Could we launch a Steam shortcut?

**Comment by MrEliptik** [comment]
I made this to be portable so I thought it would be best to have the executable in the same folder but in some cases it might not be optimal. I guess you can try with shortcut first, I think it should work. 

Batch files might not work as we're not going to get the right PID and we won't be able to follow the lifecycle of the game, but I'm not sure.

**Comment by naturally-intelligent** [comment]
Can a batch file can return the PID as it's exit value?

Anyways, haven't had any issues with this yet, but I imagine as the launcher gets more use people will want to launch steam games from it (at least in my use case), but since that is maybe a month away, I wont worry about it now. But I will report back any results for it then

**Comment by MrEliptik** [comment]
Launching an `.exe` outside of the launcher folder is definitely possible, we would just need to detect the path is not local, or even add another configuration line for external .exe.
For launching steam games or shortcuts, we can use OS.shell_open() quite easily. I'm starting a discuss here: https://github.com/MrEliptik/game_launcher/issues/21
