### ISSUE TITLE
Ability to show a game but make it not playable

### ISSUE THREAD

**Issue by MrEliptik** [MrEliptik/game_launcher#15]
In the config file we should be able to differentiate between the game being shown and playable

**Comment by Loxtir** [comment]
Would you always show the button as disabled (so greyed out if a game is not playable) or only when it is focused?
For example, the first game is playable, the others aren't.
![always_gray](https://github.com/user-attachments/assets/fa6dd971-ce44-4fe5-a883-84ab84b07b83)
![gray_on_focus](https://github.com/user-attachments/assets/347f8da8-f670-465e-a61c-4091bfa3839a)

**Comment by MrEliptik** [comment]
I think showing it greyed out all the time makes more sense. Maybe we should display a message too when the game is focused. At the top of the description, something like "not playable"
