### ISSUE TITLE
Display more information about the game

### ISSUE THREAD

**Issue by MrEliptik** [MrEliptik/game_launcher#7]
The current game description is fairly limited and it would be cool to include more information, such as release date, platform, player count, etc.. We need to move to an ini or json file for that and the UI needs to be updated

**Comment by naturally-intelligent** [comment]
I'm going to be doing something similar to this soon, including probably some kind of overhaul to the UI.

I prefer INI files because they are easier to edit by hand

**Comment by MrEliptik** [comment]
INI might be better especially for non developer you're right. Don't hesitate to share your redesign if you want to!

**Comment by naturally-intelligent** [comment]
Here is a sample config file proposal:

```[GAME]
title = "Sample Game Title"
executable = "Chore 4.exe"
capsule = "capsule.png"
background = "bg.png"
description = "Here is a text blurb. \n\n Or use description.txt."
category = ["Tools", "Tests"]
notice = "Coming Soon"
arguments = "--fullscreen --keyboard"

[SETTINGS]
order = 1
visible = true
available = true
pinned = false

[ATTRIBUTES]
singleplayer = false
multiplayer = true
coop = true
pvp = true
```

The thought here is that the standard executable, capsule, background, and description will be loaded by file.  Then, it will also look for a config file. If that is found, any values in the config file will be used instead.  I wanted to have customizable Title and more, and if there are a lot of games, to eventually have a category sort at the top. I have a working version of this in my repo, but I'm going to put a lot more work into it for a gamejam coming up end of this month. So I'll come back after that is over with what may be an almost unrecognizable version of your launcher :D

**Comment by MrEliptik** [comment]
Implemented with https://github.com/MrEliptik/game_launcher/commit/9b554170736a66fff5fb7897141dbd3023906417 
example config file can be found here: https://github.com/MrEliptik/game_launcher/blob/main/games/config_template.ini
