### ISSUE TITLE
What is the license of this source code?

### ISSUE THREAD

**Issue by DarkDes** [MrEliptik/game_launcher#9]
Hi. This is an interesting project, I would like to know what is the license for this source code? 

Is it possible to copy and modify this code for my needs? If yes, will I have to publish the source code of my version? 

Thank you!

**Comment by MrEliptik** [comment]
Hey, I just added the license, thank you for reminding me! It's MIT, you can see it in [LICENSE](https://github.com/MrEliptik/game_launcher/blob/main/LICENSE).
https://github.com/MrEliptik/game_launcher/commit/7ac27a42483afd9a985336a952e1f9f531db6b23
